language: python
cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - python: 3.5

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=$HOME/miniconda/bin:$PATH
    - export PATH=$HOME/miniconda2/bin:$PATH
    - hash -r
    - conda update --yes conda
    - conda config --add channels r
    - conda config --add channels bioconda
    # are not specific to using mini
    # - sudo rm -rf /dev/shm
    # - sudo ln -s /run/shm /dev/shm
    # This help testing code with pylab
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"


install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy matplotlib nose pandas coverage numexpr xlrd cython
  # use pip to get latest version
  - pip install easydev>=0.9.21 --upgrade
  - pip install coveralls
  - pip install tabulate
  - pip install biokit>=0.3.0 --upgrade
  - pip install bioservices>=1.4.11 --upgrade
  - conda install cutadapt pysam pyvcf snpEff --yes

# # command to run tests, e.g. python setup.py test
script:
  - python setup.py nosetests --with-coverage --cover-package sequana

after_success:
  coveralls
