language: python
cache:
  directories:
    - $HOME/.cache/pip
    #- $HOME/miniconda3
    - $HOME/.config/sequana

matrix:
  include:
    - python: 3.5

before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=$HOME/miniconda3/bin:$PATH
    - hash -r
    - conda update --yes conda
    - conda config --add channels r
    - conda config --add channels defaults
    - conda config --add channels conda-forge
    - conda config --add channels bioconda
    # This help testing code with pylab
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

install:
  - echo $TRAVIS_PYTHON_VERSION
  - conda install --yes python=$TRAVIS_PYTHON_VERSION --file requirements.txt
  - conda install --yes python=$TRAVIS_PYTHON_VERSION --file requirements_dev.txt
  # ideally, we should use requirements_pipelines but this lead to stall on
  # travis. so we provide just the following packages, required for the test
  # only
  - conda install --yes python=$TRAVIS_PYTHON_VERSION kraken bwa snpeff shustring krona
  #- conda install --yes python=$TRAVIS_PYTHON_VERSION --file requirements_pipelines.txt
  - pip install pytest-xdist # somehow needs to be installed with pip (not registered with conda)
  - pip install .

# # command to run tests, e.g. python setup.py test
script:
  - pytest -v --durations=10  test/ --cov=sequana --cov-report term --timeout 300 -n 4

after_success:
  coveralls
