name: sequana

channels:
- bioconda
- defaults
- r
- conda-forge

dependencies:
- python=3.5.0
- numpy
- pandas
- matplotlib
- scipy
- pysam
- krona
- kraken
- pillow
- sphinx
- reports
- bioservices
- pip
- easydev>=0.9.34
- shustring
- pip:
  - biokit>=0.3.2
  - ipython
  - jupyter
  - docutils<0.13.1 # https://github.com/sphinx-doc/sphinx/issues/3212

