name: sequana_env

channels:
- bioconda

dependencies:
- numpy
- pandas
- matplotlib
- scipy
- pysam
- krona
- kraken
- pillow
- ipython
- pip:
  - matplotlib
  - easydev>=0.9.30
  - bioservices
  - biokit>=0.3.2
  - mpld3
  - reports
