name: sequana_env

channels:
- bioconda
- defaults
- r
- conda-forge

dependenciies:
- python=3.5.1=0
- numpy
- pandas
- matplotlib
- scipy
- pysam
- krona
- kraken
- pillow
- ipython
- jupyter
- sphinx
- pip:
  - matplotlib
  - easydev>=0.9.30
  - bioservices
  - biokit>=0.3.2
  - mpld3
  - reports
