name: sequana_env

channels:
- bioconda

dependencies:
- numpy
- pandas
- matplotlib
- scipy
- pysam
- krona
- kraken
- pip:
  - matplotlib
  - easydev>=0.9.21
  - bioservices
  - biokit>=0.3.0
  - mpld3
  - reports
