name: sequana

channels:
- bioconda
- defaults
- r
- conda-forge

dependencies:
- python=3.5.1
- numpy
- pandas
- matplotlib
- scipy
- pysam
- krona
- kraken
- pillow
- jupyter
- sphinx
- reports
- pip
- pip:
  - bioservices
  - biokit>=0.3.2
  - ipython
