name: py35
dependencies:
- appdirs=1.4.0=py35_0
- beautifulsoup4=4.4.1=py35_0
- colorama=0.3.6=py35_0
- colormap=0.9.8=py35_0
- coverage=4.0.3=py35_0
- cycler=0.10.0=py35_0
- decorator=4.0.9=py35_0
- docutils=0.12=py35_0
- easydev=0.9.11=py35_0
- fontconfig=2.11.1=5
- freetype=2.5.5=0
- gevent=1.1rc4=py35_0
- greenlet=0.4.9=py35_0
- grequests=0.3.0=py35_1
- ipython=4.1.2=py35_0
- ipython_genutils=0.1.0=py35_0
- jinja2=2.8=py35_0
- libgfortran=3.0=0
- libpng=1.6.17=0
- libxml2=2.9.3=0
- markupsafe=0.23=py35_0
- matplotlib=1.5.1=np110py35_0
- mkl=11.3.1=0
- nose=1.3.7=py35_0
- numpy=1.10.4=py35_1
- openssl=1.0.2g=0
- pandas=0.17.1=np110py35_0
- path.py=8.1.2=py35_1
- pexpect=3.3=py35_0
- pickleshare=0.5=py35_0
- pip=8.0.3=py35_0
- pyparsing=2.0.3=py35_0
- pyqt=4.11.4=py35_1
- pysam=0.8.4=py35_0
- pysamstats=0.24.0=py35_0
- python=3.5.1=0
- python-dateutil=2.4.2=py35_0
- pytz=2015.7=py35_0
- pyyaml=3.11=py35_1
- qt=4.8.7=1
- readline=6.2=2
- requests=2.9.1=py35_0
- requests-cache=0.4.10=py35_0
- scipy=0.17.0=np110py35_2
- seqtk=r82=0
- setuptools=20.1.1=py35_0
- simplegeneric=0.8.1=py35_0
- sip=4.16.9=py35_0
- six=1.10.0=py35_0
- snakemake=3.5.5=py35_1
- sqlite=3.9.2=0
- tk=8.5.18=0
- traitlets=4.1.0=py35_0
- wheel=0.29.0=py35_0
- wrapt=1.10.6=py35_0
- xz=5.0.5=1
- yaml=0.1.6=0
- zlib=1.2.8=0
- pip:
  - biokit (/home/cokelaer/Work/github/biokit)==0.2.1
  - cutadapt==1.9.1
  - easydev (/home/cokelaer/Work/github/easydev/src)==0.9.14
  - flask==0.10.1
  - ipython-genutils==0.1.0
  - itsdangerous==0.24
  - line-profiler==1.0
  - mpld3==0.2
  - reports (/home/cokelaer/Work/github/reports/src)==0.1.0
  - sequana (/home/cokelaer/Work/github/sequana)==0.0.2
  - sequoia (/home/cokelaer/Work/github/sequoia)==0.0.2
  - werkzeug==0.11.4
  - yappi==0.94

