name: sequana

channels:
- bioconda
- defaults
- r
- conda-forge

dependencies:
- python=3.5.0
- numpy
- pandas
- matplotlib
- scipy
- pysam
- krona
- kraken
- pillow
- sphinx
- reports
- bioservices
- pip
- pip:
  - biokit>=0.3.2
  - ipython
  - jupyter
