# ============================================================================
# Config file for Quality Control
#
# ==========================================[ Sections for the users ]========
#
# One of input_directory, input_pattern and input_samples must be provided
# If input_directory provided, use it otherwise if input_pattern provided,
# use it, otherwise use input_samples.
# If input_extension provided, use it otherwise assume fastq.gz
# ============================================================================
input_directory: "%(input_directory)s"
input_extension: "%(input_extension)s"
input_pattern: "%(input_pattern)s"
input_samples:
    file1: "%(file1)s"
    file2: "%(file2)s"

# if files are required for a pipeline and are within sequana or should
# # be downloaded before the pipeline provide them in this section
# # Note that sequana and url fields are followed by itemised files or links
# using
# # the front dashes
requirements:
    - phiX174.fa


# =========================================== For testing only
# If True, only a subset of the reads (N) are used

fastq_sampling:
    do: no
    N: 2500

# =========================================== Sections related to external tools
fastqc:
    options: "--nogroup"

##################################################################
# Use by Phix_removal pipeline to remove reads with the
# phix found in the bwa_phix:reference section
#
##################################################################
bwa_mem_phix:
    do: yes
    reference_file: "phiX174.fa"
    index_algorithm: "is"
    options: '-T 30'
    threads: 2

#################################################################
# Quality trimming and adapter removal
#   - adapter_type can only be PCRFree or Nextera and used by 
#     with design_file only.
#   - design_file: a valid CSV file with mapping of index and 
#       sample name
#   - quality: 0 means no trimming, 30 means keep base with quality
#       above 30
#   - m: 20 means discard trimmed reads that are shorter than 20.
#        must be >0 and <40
#   - tool: only cutadapt supported for now
#
#   - if design_file is provided, fwd and rev are ignored
#    - mode: must be set to one of
#       - g for 5' 
#       - a for 3'
#       - b for both 5'/3'
#
#   ref: http://cutadapt.readthedocs.io/
#################################################################
adapter_removal:
    do: yes
    tool: cutadapt
    adapter_type:               # None, PCRFree, Nextera
    design_file:
    fwd:
    rev:
    m: 20                       # {"strict_min":0}
    mode: "b"                   # {"values": [b,g,a]}
    options: "-O 6 --trim-n"
    quality: 30                 # {"range": [0,40]}

########################################################### Kraken
# For taxonomy. Used in quality_control pipeline
kraken:
    do: False
    database_directory:  "%(kraken_database_directory)s"
