
samples:
    file1: "../Hm2_GTGAAA_L005_R1_001.fastq.gz"
    file2: "../Hm2_GTGAAA_L005_R2_001.fastq.gz"

project: "Hm2_GTGAAA_L005"

kraken:
    database: /home/cokelaer/Downloads/viruses/adapters
    #database: "/home/cokelaer/Work/kraken/alldbs"

