# ============================================================================
# Config file for RNA-seq
#
# ==================[ Sections for the users ]================================
#
# One of input_directory, input_pattern and input_samples must be provided
# If input_directory provided, use it otherwise if input_pattern provided,
# use it, otherwise use input_samples.
# If input_extension provided, use it otherwise assume fastq.gz
# ============================================================================
input_directory: "%(input_directory)s"
input_readtag: "%(input_readtag)s"
input_pattern: "%(input_pattern)s"
input_extension: "%(input_extension)s"
# =========================================== Sections for the users

# list of your input file
input_samples:
    file1: "%(file1)s"
    file2: "%(file2)s"

# if files are required for a pipeline and are within sequana or should
# be downloaded before the pipeline provide them in this section
# Note that sequana and url fields are followed by itemised files or links
# using the front dashes
requirements:
    - Institut_Pasteur.png



#############################################################################
# General section
#
# :Parameters:
#
# - genome_file: path to Reference Genome in fasta format
# - genome_file: path to annotation file in GFF format
# - spikes: if data contain spikes or not. May be yes or no
# - spikes_file: path to spikes in fasta format
# - merge_smrtcell: yes (or not) according to your sequencing design
# - design_file: path to design in XX format if you want to merge smrtcell
#

general:
  genome_file: /path/to/your/directory/Genomes/hg19/hg19.fa
  annotation_file : /path/to/your/directory/Genomes/hg19/hg19.gff
  spikes: yes # may be yes
  spikes_file: /path/to/your/directory/spikes.fa
  merge_smrtcell: no
  design_file: /path/to/your/directory/design.txt

#############################################################################
# Isoseq3 PacBio pipeline
# available here:  https://github.com/PacificBiosciences/IsoSeq3
#
# :Parameters:
#
# - primers: primer(+barcode) sequences in fasta format
# - options: any options recognized by different commands of isoseq3 tool
# - threads: number of threads to be used

ccs:
  options: '--noPolish --minPasses 1'
  threads: 12

lima:
  primers: /path/to/barcoded_primers
  threads: 12

refine:
  options: ''
  threads: 12

merge:
  options: ''
  threads: 12

cluster:
  options: ''
  threads: 12

polish:
  options: ''
  threads: 12

summarize:
  options: ''
  threads: 12


#############################################################################
# minimap2_mapping used to align reads against reference in fasta format
#
# :Parameters:
#
# - do: if unchecked, this rule is ignored
# - options: any options recognised by minimap2 tool
# - threads: number of threads to be used
#
minimap2_mapping:
    do: yes
    options: "-ax map-ont --secondary=no"
    threads: 12
