
input: "*fastq*"

requirements: ['Coliphage_phiX174.fa']


datadir: fastq_raw


fastqc:
    kargs: "--nogroup"

fastq_sampling:
    enable: False
    N: 100000


# Name of the Fix to be found in bwa_phix rule
bwa_phix:
    reference: Coliphage_phiX174.fa
    kargs: 


