# ============================================================================
# Config file for Quality Control
# ==========================================[ Sections for the users ]========
#
# One of input_directory, input_pattern and input_samples must be provided
# If input_directory provided, use it otherwise if input_pattern provided,
# use it, otherwise use input_samples.
# If input_extension provided, use it otherwise assume fastq.gz
# ============================================================================
input_directory: ''
input_extension: ''
input_pattern: /home/cokelaer/Work/DATA/Pacbio/test_sequana/*bam
input_readtag: _R[12]_
input_samples: CommentedMap([('file1', ''), ('file2', '')])


bam_to_fasta:
    thread: 6


######################################################
# Taxonomic analysis
#
# Provide as many databases as you want. They will be 
# used sequentially.
kraken:
    do: yes
    thread: 6
    db01_directory: toydb
    db02_directory: ''
    db03_directory: ''
    db04_directory: ''
    db05_directory: ''
    db06_directory: ''
    db07_directory: ''
    db08_directory: ''
    db09_directory: ''
    db10_directory: ''
