
samples:
    file1: ../02_3277_CGATGT_L001_R1_001.fastq.gz
    file2: ../02_3277_CGATGT_L001_R2_001.fastq.gz

project: "02_3277_CGATCT_L001"

kraken:
    database: /home/cokelaer/Downloads/viruses/adapters
    #database: "/home/cokelaer/Downloads/minikraken_20141208/"
    #database: "/home/cokelaer/Downloads/viruses/"

