# list of your input file
samples:
    file1: pKM2-EGFP-V-f_S2_L001_R1_001.fastq.gz

project: pKM2-EGFP-V-f_S2_L001

# GATK is absent in conda because it is not a free software
# You must set the GATK bin path.
# gatk_bin: "java -jar /path/to/GenomeAnalysisTK.jar"
gatk_bin: GenomeAnalysisTK

# Bwa parameter for reference mapping
bwa_ref:
    reference: pKM2-eGFP.fa
    index:
        options: '-a is'
    mem:
        options: '-T 30'
        # -R option for GATK
        read_groups: '@RG\\tID:1\\tSM:1\\tPL:illumina'
        # -t option (number thread)
        threads: 2 

# snpEff parameter
snpeff:
    do: yes
    reference:

# Software parameters

bedtools: 
    options: '-d'

freebayes:
    options: '--ploidy 1'

indel_realigner:
    do: yes
    options: ''

mark_duplicates:
    do: yes
    options: ''

report_mapping:
    do: yes
    window_size: 1001
    high_threshold: 3
    low_threshold: -3

vcf_filter:
    QUAL: 100
    FREQ: 0.7
    INFO:
        DP: '>= 10'
