# list of your input file
samples:
    file1: pKM2-EGFP-V-f_S2_L001_R1_001.fastq.gz

project: pKM2-EGFP-V-f_S2_L001

# reference
reference: pKM2-eGFP.fa

# GATK is absent in conda because it is not a free software
# You must set the GATK bin path.
# gatk_bin: "java -jar /path/to/GenomeAnalysisTK.jar"
gatk_bin: GenomeAnalysisTK

# Software parameters

bedtools: "-d"

bwa_index:
    -a: "is"

bwa_mem:
    args:
        -R: '@RG\\tID:1\\tSM:1\\tPL:illumina'
    threads: 2
    kwargs: ""

freebayes:
    --ploidy: 1

indel_realigner:
    do: yes

mark_duplicates:
    do: yes

report_mapping:
    do: yes
    window_size: 1001
    high_threshold: 3
    low_threshold: -3

vcf_filter:
    QUAL: 100
    FREQ: 0.7
    INFO:
        DP: ">= 10"
