# =========================================== Sections for the users

# list of your input file
samples:
    file1: "%(file1)s"
    file2: "%(file2)s"


project: "%(project)s"

# Bwa parameter for reference mapping
bwa_ref:
    reference: "%(reference)s"
    index:
        options: '-a is'
    mem:
        options: '-T 30'
        # -R option for GATK
        read_groups: '@RG\\tID:1\\tSM:1\\tPL:illumina'
        # -t option (number thread)
        threads: 2 

# snpEff parameter
# Results filter options:
#	-no-downstream: Do not show DOWNSTREAM changes
#	-no-intergenic: Do not show INTERGENIC changes
#	-no-intron: Do not show INTRON changes
#	-no-upstream: Do not show UPSTREAM changes
#	-no-utr: Do not show 5_PRIME_UTR or 3_PRIME_UTR changes
#	-no EffectType: Do not show 'EffectType'. This option can be used several times.
 
snpeff:
    do: no
    reference:
    options: "-no-downstream -no-upstream"

# Software parameters

bedtools: 
    options: '-d'

freebayes:
    options: '--ploidy 1'

indel_realigner:
    do: yes
    options: ''

mark_duplicates:
    do: yes
    options: ''

report_mapping:
    do: yes
    k: 2
    circular: yes
    window_size: 1001
    high_threshold: 3
    low_threshold: -3

vcf_filter:
    QUAL: 1000
    FREQ: 0.8
    INFO:
        DP: '>= 10'


